### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jaskirat111** [kslat3r/anpr-dashcam#2]
![image](https://user-images.githubusercontent.com/33426850/74101358-e50c0280-4b5e-11ea-91e2-ed8838069a34.png)

**Comment by kslat3r** [comment]
@jaskirat111 can you please confirm:

* Node.js version
* NPM version
* openalpr library version

Thanks

**Comment by jaskirat111** [comment]
Node.js Version = v8.17.0
NPM version= 6.13.4
alpr  version: 2.3.0

**Comment by jaskirat111** [comment]
the client part is running but the server part is showing this error

**Comment by kslat3r** [comment]
Hi @jaskirat111 unfortunately I am unable to replicate your issue as I cannot install the most recent version of OpenALPR on OSX 10.15.3. I'm not able to spend a lot of time look at this right now, but I'll put it on my list to Docker-ise the whole installation on Monday when I have some free time. Hoping you can wait until then :)

**Comment by kslat3r** [comment]
@jaskirat111 I have updated the app to use Docker, which seems to work fine (see the README file). However (and rightly so) the DVLA have added extra security measures to their website to stop scripts like mine from scraping. So, you will see the ANPR, but you won't get the DVLA details. YMMV, and good luck.
